export const pertanyaan = [
  {
    id: 1,
    pertanyaan: 'Apakah Anda memiliki kemampuan logika, analisis, dan pemecahan masalah yang baik?',
    programmer: true,
    software_engineer: true,
    web_developer: true,
    mobile_developer: true,
    data_scientist: true,
    cybersecurity_analyst: true,
    game_developer: true,
    system_analyst: true,
    konsultan_it: true
  },
  {
    id: 2,
    pertanyaan: 'Apakah Anda menguasai bahasa pemrograman, algoritma, dan struktur data?',
    programmer: true,
    software_engineer: true,
    web_developer: true,
    mobile_developer: true,
    data_scientist: true,
    cybersecurity_analyst: true,
    game_developer: true,
    system_analyst: true,
    konsultan_it: true
  },
  {
    id: 3,
    pertanyaan: 'Apakah Anda mampu bekerja secara tim?',
    programmer: true,
    software_engineer: true,
    web_developer: true,
    mobile_developer: true,
    data_scientist: true,
    cybersecurity_analyst: true,
    game_developer: true,
    system_analyst: true,
    konsultan_it: true
  },
  {
    id: 4,
    pertanyaan: 'Apakah Anda memiliki pengetahuan dan pengalaman dalam siklus hidup pengembangan perangkat lunak?',
    programmer: true,
    software_engineer: true,
    web_developer: true,
    mobile_developer: true,
    data_scientist: true,
    cybersecurity_analyst: true,
    game_developer: true,
    system_analyst: true,
    konsultan_it: true
  },
  {
    id: 5,
    pertanyaan: 'Apakah Anda menguasai bahasa pemrograman, framework, dan tool yang relevan?',
    programmer: true,
    software_engineer: true,
    web_developer: true,
    mobile_developer: true,
    data_scientist: true,
    cybersecurity_analyst: true,
    game_developer: true,
    system_analyst: true,
    konsultan_it: true
  },
  {
    id: 6,
    pertanyaan: 'Apakah Anda mampu beradaptasi dengan perubahan teknologi dan kebutuhan?',
    programmer: true,
    software_engineer: true,
    web_developer: true,
    mobile_developer: true,
    data_scientist: true,
    cybersecurity_analyst: true,
    game_developer: true,
    system_analyst: true,
    konsultan_it: true
  },
  {
    id: 7,
    pertanyaan: 'Apakah Anda memiliki keterampilan dalam desain web, user interface, user experience, dan responsivitas?',
    programmer: false,
    software_engineer: false,
    web_developer: true,
    mobile_developer: true,
    data_scientist: false,
    cybersecurity_analyst: false,
    game_developer: true,
    system_analyst: false,
    konsultan_it: false
  },
  {
    id: 8,
    pertanyaan: 'Apakah Anda menguasai teknologi web front-end, back-end, atau full-stack?',
    programmer: false,
    software_engineer: false,
    web_developer: true,
    mobile_developer: false,
    data_scientist: false,
    cybersecurity_analyst: false,
    game_developer: false,
    system_analyst: false,
    konsultan_it: false
  },
  {
    id: 9,
    pertanyaan: 'Apakah Anda mampu berkomunikasi dengan klien dan pengguna?',
    programmer: true,
    software_engineer: true,
    web_developer: true,
    mobile_developer: true,
    data_scientist: true,
    cybersecurity_analyst: true,
    game_developer: true,
    system_analyst: true,
    konsultan_it: true
  },
  {
    id: 10,
    pertanyaan: 'Apakah Anda memiliki keterampilan dalam desain aplikasi, user interface, user experience, dan performa?',
    programmer: false,
    software_engineer: false,
    web_developer: false,
    mobile_developer: true,
    data_scientist: false,
    cybersecurity_analyst: false,
    game_developer: true,
    system_analyst: false,
    konsultan_it: false
  },
  {
    id: 11,
    pertanyaan: 'Apakah Anda menguasai platform native, seperti Android atau iOS, atau platform cross-platform, seperti React Native atau Flutter?',
    programmer: false,
    software_engineer: false,
    web_developer: false,
    mobile_developer: true,
    data_scientist: false,
    cybersecurity_analyst: false,
    game_developer: false,
    system_analyst: false,
    konsultan_it: false
  },
  {
    id: 12,
    pertanyaan: 'Apakah Anda mampu mengikuti standar dan guideline yang berlaku?',
    programmer: true,
    software_engineer: true,
    web_developer: true,
    mobile_developer: true,
    data_scientist: true,
    cybersecurity_analyst: true,
    game_developer: true,
    system_analyst: true,
    konsultan_it: true
  },
  {
    id: 13,
    pertanyaan: 'Apakah Anda memiliki kemampuan matematika, statistik, dan analisis data yang kuat?',
    programmer: false,
    software_engineer: false,
    web_developer: false,
    mobile_developer: false,
    data_scientist: true,
    cybersecurity_analyst: false,
    game_developer: false,
    system_analyst: false,
    konsultan_it: false
  },
  {
    id: 14,
    pertanyaan: 'Apakah Anda menguasai bahasa pemrograman, seperti Python atau R, dan tool analisis data, seperti SQL, Excel, atau Tableau?',
    programmer: false,
    software_engineer: false,
    web_developer: false,
    mobile_developer: false,
    data_scientist: true,
    cybersecurity_analyst: false,
    game_developer: false,
    system_analyst: false,
    konsultan_it: false
  },
  {
    id: 15,
    pertanyaan: 'Apakah Anda mampu menyajikan hasil analisis dengan jelas dan menarik?',
    programmer: false,
    software_engineer: false,
    web_developer: false,
    mobile_developer: false,
    data_scientist: true,
    cybersecurity_analyst: false,
    game_developer: false,
    system_analyst: false,
    konsultan_it: false
  },
  {
    id: 16,
    pertanyaan: 'Apakah Anda memiliki pengetahuan dan pengalaman dalam bidang keamanan siber?',
    programmer: false,
    software_engineer: false,
    web_developer: false,
    mobile_developer: false,
    data_scientist: false,
    cybersecurity_analyst: true,
    game_developer: false,
    system_analyst: false,
    konsultan_it: false
  },
  {
    id: 17,
    pertanyaan: 'Apakah Anda menguasai konsep-konsep seperti enkripsi, firewall, antivirus, autentikasi, dan forensik digital?',
    programmer: false,
    software_engineer: false,
    web_developer: false,
    mobile_developer: false,
    data_scientist: false,
    cybersecurity_analyst: true,
    game_developer: false,
    system_analyst: false,
    konsultan_it: false
  },
  {
    id: 18,
    pertanyaan: 'Apakah Anda mampu mencegah, mendeteksi, dan menangani insiden keamanan siber?',
    programmer: false,
    software_engineer: false,
    web_developer: false,
    mobile_developer: false,
    data_scientist: false,
    cybersecurity_analyst: true,
    game_developer: false,
    system_analyst: false,
    konsultan_it: false
  },
  {
    id: 19,
    pertanyaan: 'Apakah Anda memiliki kreativitas, imajinasi, dan passion dalam membuat game?',
    programmer: false,
    software_engineer: false,
    web_developer: false,
    mobile_developer: false,
    data_scientist: false,
    cybersecurity_analyst: false,
    game_developer: true,
    system_analyst: false,
    konsultan_it: false
  },
  {
    id: 20,
    pertanyaan: 'Apakah Anda menguasai bahasa pemrograman, desain grafis, animasi, audio, fisika, dan matematika?',
    programmer: false,
    software_engineer: false,
    web_developer: false,
    mobile_developer: false,
    data_scientist: false,
    cybersecurity_analyst: false,
    game_developer: true,
    system_analyst: false,
    konsultan_it: false
  },
  {
    id: 21,
    pertanyaan: 'Apakah Anda mampu bekerja dalam tim multidisiplin?',
    programmer: false,
    software_engineer: false,
    web_developer: false,
    mobile_developer: false,
    data_scientist: false,
    cybersecurity_analyst: false,
    game_developer: true,
    system_analyst: false,
    konsultan_it: false
  },
  {
    id: 22,
    pertanyaan: 'Apakah Anda memiliki kemampuan analisis, komunikasi, dan negosiasi yang baik?',
    programmer: true,
    software_engineer: true,
    web_developer: true,
    mobile_developer: true,
    data_scientist: true,
    cybersecurity_analyst: true,
    game_developer: true,
    system_analyst: true,
    konsultan_it: true
  },
  {
    id: 23,
    pertanyaan: 'Apakah Anda menguasai konsep-konsep sistem informasi, basis data, dan rekayasa perangkat lunak?',
    programmer: false,
    software_engineer: false,
    web_developer: false,
    mobile_developer: false,
    data_scientist: false,
    cybersecurity_analyst: false,
    game_developer: false,
    system_analyst: true,
    konsultan_it: true
  },
  {
    id: 24,
    pertanyaan: 'Apakah Anda mampu bekerja sama dengan programmer, software engineer, atau profesional IT lainnya?',
    programmer: false,
    software_engineer: false,
    web_developer: false,
    mobile_developer: false,
    data_scientist: false,
    cybersecurity_analyst: false,
    game_developer: false,
    system_analyst: true,
    konsultan_it: true
  },
  {
    id: 25,
    pertanyaan: 'Apakah Anda memiliki pengetahuan dan pengalaman dalam bidang bisnis, manajemen, atau konsultasi?',
    programmer: false,
    software_engineer: false,
    web_developer: false,
    mobile_developer: false,
    data_scientist: false,
    cybersecurity_analyst: false,
    game_developer: false,
    system_analyst: false,
    konsultan_it: true
  },
  {
    id: 26,
    pertanyaan: 'Apakah Anda mampu memberikan saran, solusi, atau rekomendasi yang sesuai dengan kebutuhan klien?',
    programmer: false,
    software_engineer: false,
    web_developer: false,
    mobile_developer: false,
    data_scientist: false,
    cybersecurity_analyst: false,
    game_developer: false,
    system_analyst: false,
    konsultan_it: true
  },
  {
    id: 27,
    pertanyaan: 'Apakah Anda mampu mengelola proyek, anggaran, dan sumber daya?',
    programmer: false,
    software_engineer: false,
    web_developer: false,
    mobile_developer: false,
    data_scientist: false,
    cybersecurity_analyst: false,
    game_developer: false,
    system_analyst: false,
    konsultan_it: true
  }
]
